### PR TITLE
Update to react 15 (and all the other packages)

### LINKED ISSUE #20: findDOMNode exploding with react 15
Getting

```
Uncaught (in promise) Error: traverseParentPath(....): Cannot traverse from and to the same ID, ``.
```

Caused by findDOMNode in Cell.jsx

Looks like replacing it with an element ref should fix it?

### PR DESCRIPTION
**Pull request by gavmck**
Hey there,

I was trying to use this plugin on a react 15.4.2 app and having difficulties with the call to findDOMNode. In the process of updating, it led me down a rabbithole where everything needed updating/tweaking.

Should be all good to go now and have switched findDOMNode to use ref function instead.

Should fix #20

### CODE REVIEW

**Comment by zackify** [comment]
Looks good to me, one little thing though "The ref attribute takes a callback function, and the callback will be executed immediately after the component is mounted or unmounted." Is this before componentDidMount is called? I'm assuming so, which means everything would work perfect. Good job

**Comment by gavmck** [comment]
Yep, should only be called after we know what's in render.

```
componentDidMount() is invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here. 
```
https://facebook.github.io/react/docs/react-component.html#componentdidmount

**Comment by gavmck** [comment]
Oh there's a more relevant example in the docs here: https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-class-component

**Comment by dphaener** [comment]
@gavmck This looks good! Thanks for working on this. I'm going to go ahead and merge and just do a few smoke tests locally, and if everything looks good I'll release shortly thereafter.

**Pull request merged**
